name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Run tests && Install dependencies
        run: |
          python -m unittest test_producto.py 
          pip install -r requirements.txt

      - name: Run linter
        run: |
            pip install flake8
            flake8 .

      - name: Run tests
        run: |
          pip install pytest
          pytest

      - name: Run code analysis
        run: |
          pip install pylint
          pylint producto.py

